name: dartwork
version: 0.1.0
author: Ilya Kharlamov <ilya.kharlamov@gmail.com>
description: A general-purpose algoritms library includes Bag, Queue, Stack, Graph, Digraph, DirectedCycle, DepthFirstOrder, SymbolGraph, SymbolDigraph, SymbolTable, Topological sort
homepage: https://github.com/ilyakharlamov/dartwork
dependencies:
  js: '>=0.0.24 <0.0.25'
  range: '>=1.1.0'
  unittest: '>=0.6.14+2 <0.6.15'
